# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contract_delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_contract_delete(object):
    def setupUi(self, contract_delete):
        contract_delete.setObjectName("contract_delete")
        contract_delete.resize(278, 75)
        self.label = QtWidgets.QLabel(contract_delete)
        self.label.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label.setObjectName("label")
        self.pushButton_contract_delete = QtWidgets.QPushButton(contract_delete)
        self.pushButton_contract_delete.setGeometry(QtCore.QRect(100, 40, 93, 28))
        self.pushButton_contract_delete.setObjectName("pushButton_contract_delete")
        self.lineEdit_contract = QtWidgets.QLineEdit(contract_delete)
        self.lineEdit_contract.setGeometry(QtCore.QRect(160, 10, 113, 22))
        self.lineEdit_contract.setObjectName("lineEdit_contract")

        self.retranslateUi(contract_delete)
        QtCore.QMetaObject.connectSlotsByName(contract_delete)

    def retranslateUi(self, contract_delete):
        _translate = QtCore.QCoreApplication.translate
        contract_delete.setWindowTitle(_translate("contract_delete", "Delete contract"))
        self.label.setText(_translate("contract_delete", "Enter id:"))
        self.pushButton_contract_delete.setText(_translate("contract_delete", "Delete"))
