# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contract_insert.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_contract_insert(object):
    def setupUi(self, contract_insert):
        contract_insert.setObjectName("contract_insert")
        contract_insert.resize(283, 162)
        self.label = QtWidgets.QLabel(contract_insert)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(contract_insert)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 151, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(contract_insert)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(contract_insert)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 121, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_contract_id = QtWidgets.QLineEdit(contract_insert)
        self.lineEdit_contract_id.setGeometry(QtCore.QRect(160, 10, 113, 22))
        self.lineEdit_contract_id.setObjectName("lineEdit_contract_id")
        self.lineEdit_contract_supplier = QtWidgets.QLineEdit(contract_insert)
        self.lineEdit_contract_supplier.setGeometry(QtCore.QRect(160, 40, 113, 22))
        self.lineEdit_contract_supplier.setObjectName("lineEdit_contract_supplier")
        self.lineEdit_contract_title = QtWidgets.QLineEdit(contract_insert)
        self.lineEdit_contract_title.setGeometry(QtCore.QRect(160, 70, 113, 22))
        self.lineEdit_contract_title.setObjectName("lineEdit_contract_title")
        self.lineEdit_contract_note = QtWidgets.QLineEdit(contract_insert)
        self.lineEdit_contract_note.setGeometry(QtCore.QRect(160, 100, 113, 22))
        self.lineEdit_contract_note.setObjectName("lineEdit_contract_note")
        self.pushButton_contract_insert = QtWidgets.QPushButton(contract_insert)
        self.pushButton_contract_insert.setGeometry(QtCore.QRect(100, 129, 93, 28))
        self.pushButton_contract_insert.setObjectName("pushButton_contract_insert")

        self.retranslateUi(contract_insert)
        QtCore.QMetaObject.connectSlotsByName(contract_insert)

    def retranslateUi(self, contract_insert):
        _translate = QtCore.QCoreApplication.translate
        contract_insert.setWindowTitle(_translate("contract_insert", "Insert to contract"))
        self.label.setText(_translate("contract_insert", "Enter id:"))
        self.label_2.setText(_translate("contract_insert", "Enter supplier:"))
        self.label_3.setText(_translate("contract_insert", "Enter title:"))
        self.label_4.setText(_translate("contract_insert", "Enter note:"))
        self.pushButton_contract_insert.setText(_translate("contract_insert", "Insert"))
