# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_proced_show.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_first_proced_show(object):
    def setupUi(self, first_proced_show):
        first_proced_show.setObjectName("first_proced_show")
        first_proced_show.resize(754, 204)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(first_proced_show.sizePolicy().hasHeightForWidth())
        first_proced_show.setSizePolicy(sizePolicy)
        self.tableWidget = QtWidgets.QTableWidget(first_proced_show)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 931, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)

        self.retranslateUi(first_proced_show)
        QtCore.QMetaObject.connectSlotsByName(first_proced_show)

    def retranslateUi(self, first_proced_show):
        _translate = QtCore.QCoreApplication.translate
        first_proced_show.setWindowTitle(_translate("first_proced_show", "GetTotalCostByContractNumber"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("first_proced_show", "product"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("first_proced_show", "amount"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("first_proced_show", "price"))
