# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'legal_insert.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_legal_insert(object):
    def setupUi(self, legal_insert):
        legal_insert.setObjectName("legal_insert")
        legal_insert.resize(283, 135)
        self.label = QtWidgets.QLabel(legal_insert)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(legal_insert)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 151, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(legal_insert)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_legal_id = QtWidgets.QLineEdit(legal_insert)
        self.lineEdit_legal_id.setGeometry(QtCore.QRect(160, 10, 113, 22))
        self.lineEdit_legal_id.setObjectName("lineEdit_legal_id")
        self.lineEdit_legal_tax = QtWidgets.QLineEdit(legal_insert)
        self.lineEdit_legal_tax.setGeometry(QtCore.QRect(160, 40, 113, 22))
        self.lineEdit_legal_tax.setObjectName("lineEdit_legal_tax")
        self.lineEdit_legal_vat = QtWidgets.QLineEdit(legal_insert)
        self.lineEdit_legal_vat.setGeometry(QtCore.QRect(160, 70, 113, 22))
        self.lineEdit_legal_vat.setObjectName("lineEdit_legal_vat")
        self.pushButton_legal_insert = QtWidgets.QPushButton(legal_insert)
        self.pushButton_legal_insert.setGeometry(QtCore.QRect(50, 100, 93, 28))
        self.pushButton_legal_insert.setObjectName("pushButton_legal_insert")
        self.pushButton_legal_update = QtWidgets.QPushButton(legal_insert)
        self.pushButton_legal_update.setGeometry(QtCore.QRect(150, 100, 93, 28))
        self.pushButton_legal_update.setObjectName("pushButton_legal_update")
        self.label_4 = QtWidgets.QLabel(legal_insert)
        self.label_4.setGeometry(QtCore.QRect(140, 70, 21, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(legal_insert)
        QtCore.QMetaObject.connectSlotsByName(legal_insert)

    def retranslateUi(self, legal_insert):
        _translate = QtCore.QCoreApplication.translate
        legal_insert.setWindowTitle(_translate("legal_insert", "Insert to legal supplier"))
        self.label.setText(_translate("legal_insert", "Enter id:"))
        self.label_2.setText(_translate("legal_insert", "Enter tax number:"))
        self.label_3.setText(_translate("legal_insert", "Enter vat number:"))
        self.pushButton_legal_insert.setText(_translate("legal_insert", "Insert"))
        self.pushButton_legal_update.setText(_translate("legal_insert", "Update"))
        self.label_4.setText(_translate("legal_insert", "UA"))
