# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'legal_delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_legal_delete(object):
    def setupUi(self, legal_delete):
        legal_delete.setObjectName("legal_delete")
        legal_delete.resize(278, 75)
        self.label = QtWidgets.QLabel(legal_delete)
        self.label.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label.setObjectName("label")
        self.pushButton_legal_delete = QtWidgets.QPushButton(legal_delete)
        self.pushButton_legal_delete.setGeometry(QtCore.QRect(100, 40, 93, 28))
        self.pushButton_legal_delete.setObjectName("pushButton_legal_delete")
        self.lineEdit_legal = QtWidgets.QLineEdit(legal_delete)
        self.lineEdit_legal.setGeometry(QtCore.QRect(160, 10, 113, 22))
        self.lineEdit_legal.setObjectName("lineEdit_legal")

        self.retranslateUi(legal_delete)
        QtCore.QMetaObject.connectSlotsByName(legal_delete)

    def retranslateUi(self, legal_delete):
        _translate = QtCore.QCoreApplication.translate
        legal_delete.setWindowTitle(_translate("legal_delete", "Delete legal supplier"))
        self.label.setText(_translate("legal_delete", "Enter id:"))
        self.pushButton_legal_delete.setText(_translate("legal_delete", "Delete"))
