# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_window(object):
    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.resize(191, 113)
        self.login_line = QtWidgets.QLineEdit(login_window)
        self.login_line.setGeometry(QtCore.QRect(60, 10, 113, 22))
        self.login_line.setObjectName("login_line")
        self.password_line = QtWidgets.QLineEdit(login_window)
        self.password_line.setGeometry(QtCore.QRect(60, 50, 113, 22))
        self.password_line.setObjectName("password_line")
        self.label = QtWidgets.QLabel(login_window)
        self.label.setGeometry(QtCore.QRect(10, 10, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(login_window)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 55, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton_login_commit = QtWidgets.QPushButton(login_window)
        self.pushButton_login_commit.setGeometry(QtCore.QRect(40, 80, 93, 28))
        self.pushButton_login_commit.setObjectName("pushButton_login_commit")

        self.retranslateUi(login_window)
        QtCore.QMetaObject.connectSlotsByName(login_window)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "Dialog"))
        self.label.setText(_translate("login_window", "Login"))
        self.label_2.setText(_translate("login_window", "Passord"))
        self.pushButton_login_commit.setText(_translate("login_window", "Login"))
