# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 215)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tab = QtWidgets.QTabWidget(self.centralwidget)
        self.tab.setGeometry(QtCore.QRect(0, 0, 761, 501))
        self.tab.setObjectName("tab")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.pushButton_supplier_insert = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_supplier_insert.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.pushButton_supplier_insert.setObjectName("pushButton_supplier_insert")
        self.pushButton_supplier_update = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_supplier_update.setGeometry(QtCore.QRect(10, 50, 93, 28))
        self.pushButton_supplier_update.setObjectName("pushButton_supplier_update")
        self.pushButton_supplier_delete = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_supplier_delete.setGeometry(QtCore.QRect(10, 90, 93, 28))
        self.pushButton_supplier_delete.setObjectName("pushButton_supplier_delete")
        self.tab.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.pushButton_contract_insert = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_contract_insert.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.pushButton_contract_insert.setObjectName("pushButton_contract_insert")
        self.pushButton_contract_update = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_contract_update.setGeometry(QtCore.QRect(10, 50, 93, 28))
        self.pushButton_contract_update.setObjectName("pushButton_contract_update")
        self.pushButton_contract_delete = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_contract_delete.setGeometry(QtCore.QRect(10, 90, 93, 28))
        self.pushButton_contract_delete.setObjectName("pushButton_contract_delete")
        self.tab.addTab(self.tab_6, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.pushButton_product_delete = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_product_delete.setGeometry(QtCore.QRect(10, 90, 93, 28))
        self.pushButton_product_delete.setObjectName("pushButton_product_delete")
        self.pushButton_product_update = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_product_update.setGeometry(QtCore.QRect(10, 50, 93, 28))
        self.pushButton_product_update.setObjectName("pushButton_product_update")
        self.pushButton_product_insert = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_product_insert.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.pushButton_product_insert.setObjectName("pushButton_product_insert")
        self.tab.addTab(self.tab_9, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 26))
        self.menubar.setObjectName("menubar")
        self.menuLogin = QtWidgets.QMenu(self.menubar)
        self.menuLogin.setObjectName("menuLogin")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.open_login_screen = QtWidgets.QAction(MainWindow)
        self.open_login_screen.setObjectName("open_login_screen")
        self.show_db = QtWidgets.QAction(MainWindow)
        self.show_db.setObjectName("show_db")
        self.menuLogin.addAction(self.open_login_screen)
        self.menuLogin.addAction(self.show_db)
        self.menubar.addAction(self.menuLogin.menuAction())

        self.retranslateUi(MainWindow)
        self.tab.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Delivery"))
        self.pushButton_supplier_insert.setText(_translate("MainWindow", "Insert"))
        self.pushButton_supplier_update.setText(_translate("MainWindow", "Update"))
        self.pushButton_supplier_delete.setText(_translate("MainWindow", "Delete"))
        self.tab.setTabText(self.tab.indexOf(self.tab_5), _translate("MainWindow", "supplier"))
        self.pushButton_contract_insert.setText(_translate("MainWindow", "Insert"))
        self.pushButton_contract_update.setText(_translate("MainWindow", "Update"))
        self.pushButton_contract_delete.setText(_translate("MainWindow", "Delete"))
        self.tab.setTabText(self.tab.indexOf(self.tab_6), _translate("MainWindow", "contract"))
        self.pushButton_product_delete.setText(_translate("MainWindow", "Delete"))
        self.pushButton_product_update.setText(_translate("MainWindow", "Update"))
        self.pushButton_product_insert.setText(_translate("MainWindow", "Insert"))
        self.tab.setTabText(self.tab.indexOf(self.tab_9), _translate("MainWindow", "product"))
        self.menuLogin.setTitle(_translate("MainWindow", "Actions"))
        self.open_login_screen.setText(_translate("MainWindow", "Login"))
        self.show_db.setText(_translate("MainWindow", "Show DB"))
