# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'private_insert.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_private_insert(object):
    def setupUi(self, private_insert):
        private_insert.setObjectName("private_insert")
        private_insert.resize(283, 206)
        self.label = QtWidgets.QLabel(private_insert)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(private_insert)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 151, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(private_insert)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_private_id = QtWidgets.QLineEdit(private_insert)
        self.lineEdit_private_id.setGeometry(QtCore.QRect(160, 10, 113, 22))
        self.lineEdit_private_id.setObjectName("lineEdit_private_id")
        self.lineEdit_private_last = QtWidgets.QLineEdit(private_insert)
        self.lineEdit_private_last.setGeometry(QtCore.QRect(160, 40, 113, 22))
        self.lineEdit_private_last.setObjectName("lineEdit_private_last")
        self.lineEdit_private_first = QtWidgets.QLineEdit(private_insert)
        self.lineEdit_private_first.setGeometry(QtCore.QRect(160, 70, 113, 22))
        self.lineEdit_private_first.setObjectName("lineEdit_private_first")
        self.pushButton_private_insert = QtWidgets.QPushButton(private_insert)
        self.pushButton_private_insert.setGeometry(QtCore.QRect(50, 160, 93, 28))
        self.pushButton_private_insert.setObjectName("pushButton_private_insert")
        self.pushButton_private_update = QtWidgets.QPushButton(private_insert)
        self.pushButton_private_update.setGeometry(QtCore.QRect(150, 160, 93, 28))
        self.pushButton_private_update.setObjectName("pushButton_private_update")
        self.label_4 = QtWidgets.QLabel(private_insert)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 121, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(private_insert)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 111, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_private_second = QtWidgets.QLineEdit(private_insert)
        self.lineEdit_private_second.setGeometry(QtCore.QRect(160, 100, 113, 22))
        self.lineEdit_private_second.setObjectName("lineEdit_private_second")
        self.lineEdit_private_number = QtWidgets.QLineEdit(private_insert)
        self.lineEdit_private_number.setGeometry(QtCore.QRect(160, 130, 113, 22))
        self.lineEdit_private_number.setObjectName("lineEdit_private_number")

        self.retranslateUi(private_insert)
        QtCore.QMetaObject.connectSlotsByName(private_insert)

    def retranslateUi(self, private_insert):
        _translate = QtCore.QCoreApplication.translate
        private_insert.setWindowTitle(_translate("private_insert", "Insert to private supplier"))
        self.label.setText(_translate("private_insert", "Enter id:"))
        self.label_2.setText(_translate("private_insert", "Enter last name:"))
        self.label_3.setText(_translate("private_insert", "Enter first name:"))
        self.pushButton_private_insert.setText(_translate("private_insert", "Insert"))
        self.pushButton_private_update.setText(_translate("private_insert", "Update"))
        self.label_4.setText(_translate("private_insert", "Enter second name:"))
        self.label_5.setText(_translate("private_insert", "Enter reg number:"))
