# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'product_delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_product_delete(object):
    def setupUi(self, product_delete):
        product_delete.setObjectName("product_delete")
        product_delete.resize(278, 75)
        self.label = QtWidgets.QLabel(product_delete)
        self.label.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label.setObjectName("label")
        self.pushButton_product_delete = QtWidgets.QPushButton(product_delete)
        self.pushButton_product_delete.setGeometry(QtCore.QRect(100, 40, 93, 28))
        self.pushButton_product_delete.setObjectName("pushButton_product_delete")
        self.lineEdit_product = QtWidgets.QLineEdit(product_delete)
        self.lineEdit_product.setGeometry(QtCore.QRect(160, 10, 113, 22))
        self.lineEdit_product.setObjectName("lineEdit_product")

        self.retranslateUi(product_delete)
        QtCore.QMetaObject.connectSlotsByName(product_delete)

    def retranslateUi(self, product_delete):
        _translate = QtCore.QCoreApplication.translate
        product_delete.setWindowTitle(_translate("product_delete", "Delete product"))
        self.label.setText(_translate("product_delete", "Enter product:"))
        self.pushButton_product_delete.setText(_translate("product_delete", "Delete"))
