# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supplier_insert.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_supplier_insert(object):
    def setupUi(self, supplier_insert):
        supplier_insert.setObjectName("supplier_insert")
        supplier_insert.resize(283, 135)
        self.label = QtWidgets.QLabel(supplier_insert)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(supplier_insert)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 151, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(supplier_insert)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_supplier_id = QtWidgets.QLineEdit(supplier_insert)
        self.lineEdit_supplier_id.setGeometry(QtCore.QRect(160, 10, 113, 22))
        self.lineEdit_supplier_id.setObjectName("lineEdit_supplier_id")
        self.lineEdit_supplier_name = QtWidgets.QLineEdit(supplier_insert)
        self.lineEdit_supplier_name.setGeometry(QtCore.QRect(160, 40, 113, 22))
        self.lineEdit_supplier_name.setObjectName("lineEdit_supplier_name")
        self.lineEdit_supplier_address = QtWidgets.QLineEdit(supplier_insert)
        self.lineEdit_supplier_address.setGeometry(QtCore.QRect(160, 70, 113, 22))
        self.lineEdit_supplier_address.setObjectName("lineEdit_supplier_address")
        self.pushButton_supplier_insert = QtWidgets.QPushButton(supplier_insert)
        self.pushButton_supplier_insert.setGeometry(QtCore.QRect(100, 100, 93, 28))
        self.pushButton_supplier_insert.setObjectName("pushButton_supplier_insert")

        self.retranslateUi(supplier_insert)
        QtCore.QMetaObject.connectSlotsByName(supplier_insert)

    def retranslateUi(self, supplier_insert):
        _translate = QtCore.QCoreApplication.translate
        supplier_insert.setWindowTitle(_translate("supplier_insert", "Insert to supplier"))
        self.label.setText(_translate("supplier_insert", "Enter id:"))
        self.label_2.setText(_translate("supplier_insert", "Enter name:"))
        self.label_3.setText(_translate("supplier_insert", "Enter address:"))
        self.pushButton_supplier_insert.setText(_translate("supplier_insert", "Insert"))
