# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supplier_delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_supplier_delete(object):
    def setupUi(self, supplier_delete):
        supplier_delete.setObjectName("supplier_delete")
        supplier_delete.resize(278, 75)
        self.label = QtWidgets.QLabel(supplier_delete)
        self.label.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label.setObjectName("label")
        self.pushButton_supplier_delete = QtWidgets.QPushButton(supplier_delete)
        self.pushButton_supplier_delete.setGeometry(QtCore.QRect(100, 40, 93, 28))
        self.pushButton_supplier_delete.setObjectName("pushButton_supplier_delete")
        self.lineEdit_supplier = QtWidgets.QLineEdit(supplier_delete)
        self.lineEdit_supplier.setGeometry(QtCore.QRect(160, 10, 113, 22))
        self.lineEdit_supplier.setObjectName("lineEdit_supplier")

        self.retranslateUi(supplier_delete)
        QtCore.QMetaObject.connectSlotsByName(supplier_delete)

    def retranslateUi(self, supplier_delete):
        _translate = QtCore.QCoreApplication.translate
        supplier_delete.setWindowTitle(_translate("supplier_delete", "Delete supplier"))
        self.label.setText(_translate("supplier_delete", "Enter id:"))
        self.pushButton_supplier_delete.setText(_translate("supplier_delete", "Delete"))
